"""User-adjustable settings for the hand gesture project."""

CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
MAX_HANDS = 2
MODEL_PATH = "models/hand_landmarker.task"

CAMERA_WINDOW_NAME = "AI Hand Gesture Recognition — Camera"
ANALYSIS_WINDOW_NAME = "Gesture Recognition Analysis"
CAMERA_WINDOW_WIDTH = 800
CAMERA_WINDOW_HEIGHT = 600
ANALYSIS_WINDOW_WIDTH = 520
ANALYSIS_WINDOW_HEIGHT = 720
WINDOW_GAP = 20

MIN_DETECTION_CONFIDENCE = 0.5
MIN_PRESENCE_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5
MIRROR_CAMERA = True

